### ISSUE TITLE
favicons not showing as in bookmark pane

### ISSUE THREAD

**Issue by GreenItSolutions** [mignz/GlobalTab#5]
In Firefox only, favicos are not represent as in the bookmark pane. No pb on Chrome
I give you a screenshot for more convenience.
![kazam_screenshot_00005](https://user-images.githubusercontent.com/15212645/38219812-b5d0fa36-36d7-11e8-92ab-90fee8975c9f.png)

**Comment by mignz** [comment]
The issue here is that those links are local websites. In firefox, I use the address `https://s2.googleusercontent.com/s2/favicons?domain_url=...` to obtain an icon and it falls back to a default icon because the website is not accessible. When I get some time I'll try to find an equivalent solution to Chrome which caches the favicons and then take a look at your other posted issues.
